"""added running_time to song model

Revision ID: dd277d5eefe4
Revises: 52cd28f2fff4
Create Date: 2023-04-06 14:21:37.387507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd277d5eefe4'
down_revision = '52cd28f2fff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('running_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('running_time')

    # ### end Alembic commands ###
